- name: Deploy static HTML page
  hosts: webserver
  become: true

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy index.html to Nginx root
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
        mode: '0644'
